// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvK-GSI4VoyYBLeXYl5dPI48P6dX25Ec',
    appId: '1:644878947057:web:084022cdaf1789d16dcf50',
    messagingSenderId: '644878947057',
    projectId: 'agriculture-91534',
    authDomain: 'agriculture-91534.firebaseapp.com',
    storageBucket: 'agriculture-91534.firebasestorage.app',
    measurementId: 'G-D49G7E7LNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVI9dGaOpM-3LI3Cua8Cw5UnSjpafLhF4',
    appId: '1:644878947057:android:739c9425ada2a0076dcf50',
    messagingSenderId: '644878947057',
    projectId: 'agriculture-91534',
    storageBucket: 'agriculture-91534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJIKR-0j88oswpxOrlNo2RKrXdjBlE_k',
    appId: '1:644878947057:ios:85f1b712c68dafe36dcf50',
    messagingSenderId: '644878947057',
    projectId: 'agriculture-91534',
    storageBucket: 'agriculture-91534.firebasestorage.app',
    iosBundleId: 'com.taskmanager.frontend',
  );
}
